function [ im ] = myInsertText( im, str )
    im = insertText(im,...
        [5,5],...
        str,...
        'FontSize',22,...
        'BoxColor','black',...
        'BoxOpacity',0.7,...
        'TextColor','white');
end

